#!/usr/bin/env bash
#This is a Bash script that gives you information about the holbertonschool file.

file=holbertonschool

if [ -e "$file" ];then
	echo "$file file exists"
	
	if [ -s $file ]; then
		echo "$file file is not empty"
	else 
		echo "$file file is empty"
	fi

	if [ -f $file ]; then
		echo "$file is a regular file"
	else
		echo " "
	fi
else 
    echo "$file does not exist."
    
fi

